In [2]:
from vnstock3 import * 
from vnstock3 import Vnstock

    Khi tiếp tục sử dụng Vnstock3, bạn xác nhận rằng bạn đã đọc, hiểu và đồng ý với Chính sách quyền riêng tư và Điều khoản, điều kiện về giấy phép sử dụng Vnstock3.

    Chi tiết:

    - Giấy phép sử dụng phần mềm: https://vnstocks.com/docs/tai-lieu/giay-phep-su-dung
    - Chính sách quyền riêng tư: https://vnstocks.com/docs/tai-lieu/chinh-sach-quyen-rieng-tu

In [3]:
import pandas as pd
import numpy as np

In [4]:
stock = Vnstock().stock(symbol = 'ACB', source = 'TCBS')

In [5]:
'https://s.cafef.vn/bao-cao-tai-chinh-chung-khoan/shs/incsta/2024/2/0/0/cong-ty-co-phan-chung-khoan-sai-gon-ha-noi.chn'

'https://s.cafef.vn/bao-cao-tai-chinh-chung-khoan/shs/incsta/2024/2/0/0/cong-ty-co-phan-chung-khoan-sai-gon-ha-noi.chn'

In [6]:
stock.listing.symbols_by_group('HNX30')

0     BVS
1     CAP
2     CEO
3     DHT
4     DTD
5     DVM
6     DXP
7     HLD
8     HUT
9     IDC
10    L14
11    L18
12    LAS
13    LHC
14    MBS
15    NTP
16    NVB
17    PLC
18    PSD
19    PVC
20    PVG
21    PVS
22    SHS
23    SLS
24    TIG
25    TMB
26    TNG
27    TVD
28    VC3
29    VCS
Name: symbol, dtype: object

In [7]:
df1 = pd.read_csv('sample_data/bank_financial_report_2.csv')
df2 = pd.read_csv('sample_data/non_bank_financial_report_2.csv')

df3 = pd.concat([df1, df2])
df3

       stock_code category_code    year  quarter       data
0             BID        IS_001  2020.0      0.0  100687502
1             BID        IS_001  2021.0      0.0  101007908
2             BID        IS_001  2022.0      0.0  121110719
3             BID        IS_001  2023.0      0.0  152761316
4             BID        IS_010  2020.0      0.0    7992789
...           ...           ...     ...      ...        ...
116639        PVC        CF_070  2023.0      2.0     212974
116640        PVC        CF_070  2021.0      3.0     153642
116641        PVC        CF_070  2021.0      4.0     202784
116642        PVC        CF_070  2022.0      1.0     173548
116643        PVC        CF_070  2022.0      2.0     165707

[154358 rows x 5 columns]

In [8]:
symbols = df3['stock_code'].unique()
symbols

array(['BID', 'CTG', 'VCB', 'ACB', 'MBB', 'HDB', 'TPB', 'VPB', 'STB',
       'TCB', 'SHB', 'VIB', 'ABB', 'LPB', 'ORS', 'VIX', 'MBS', 'VND',
       'SSI', 'MWG', 'VNM', 'HPG', 'VHM', 'FPT', 'MSN', 'GAS', 'VRE',
       'VJC', 'VIC', 'PLX', 'SAB', 'POW', 'GVR', 'BCM', 'TCH', 'CEO',
       'HUT', 'NVL', 'DBC', 'SAF', 'VTP', 'PVT', 'FRT', 'DGC', 'DCM',
       'NKG', 'CMC', 'VGI', 'PVC'], dtype=object)

In [9]:
vn30_symbols = stock.listing.symbols_by_group('VN30')
company_overviews = []
# Iterate through each symbol and print company information
for symbol in symbols:
    company = Vnstock().stock(symbol=symbol, source='TCBS').company
    company_overview = company.overview()
    company_overview['symbol'] = symbol
    company_overviews.append(company_overview)

df_company_overviews = pd.concat(company_overviews, ignore_index=True)
# Display the concatenated DataFrame
df_company_overviews.head()

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

,exchange,industry,company_type,no_shareholders,foreign_percent,outstanding_share,issue_share,established_year,no_employees,stock_rating,delta_in_week,delta_in_month,delta_in_year,short_name,website,industry_id,industry_id_v2,symbol
0,HOSE,Ngân hàng,NH,27603,0.171,5700.4,5700.4,1993,29228,3.0,0.011,0.015,0.234,BIDV,https://www.bidv.com.vn,289,8355,BID
1,HOSE,Ngân hàng,NH,53928,0.265,5370.0,5370.0,1988,24698,3.3,0.011,0.017,0.291,VietinBank,http://www.vietinbank.vn,289,8355,CTG
2,HOSE,Ngân hàng,NH,25183,0.234,5589.1,5589.1,2008,23992,3.0,0.003,-0.001,-0.056,Vietcombank,https://vietcombank.com.vn,289,8355,VCB
3,HOSE,Ngân hàng,NH,60034,0.300,4466.7,4466.7,2006,13110,3.0,-0.002,0.045,0.250,ACB,https://www.acb.com.vn,289,8355,ACB
4,HOSE,Ngân hàng,NH,121463,0.232,5306.3,5287.1,1994,17103,3.5,0.016,0.046,0.327,MBBank,https://www.mbbank.com.vn,289,8355,MBB

In [10]:
df_company_overviews.drop(columns = ['company_type','outstanding_share','established_year','no_employees','delta_in_week','delta_in_month','delta_in_year','short_name','industry_id','industry_id_v2'], inplace = True)

In [11]:
df_company_overviews['issue_share'] *= 1_000_000
df_company_overviews.head()

,exchange,industry,no_shareholders,foreign_percent,issue_share,stock_rating,website,symbol
0,HOSE,Ngân hàng,27603,0.171,5.700400e+09,3.0,https://www.bidv.com.vn,BID
1,HOSE,Ngân hàng,53928,0.265,5.370000e+09,3.3,http://www.vietinbank.vn,CTG
2,HOSE,Ngân hàng,25183,0.234,5.589100e+09,3.0,https://vietcombank.com.vn,VCB
3,HOSE,Ngân hàng,60034,0.300,4.466700e+09,3.0,https://www.acb.com.vn,ACB
4,HOSE,Ngân hàng,121463,0.232,5.287100e+09,3.5,https://www.mbbank.com.vn,MBB

In [12]:
df_company_overviews

,exchange,industry,no_shareholders,foreign_percent,issue_share,stock_rating,website,symbol
0,HOSE,Ngân hàng,27603,0.171,5.700400e+09,3.0,https://www.bidv.com.vn,BID
1,HOSE,Ngân hàng,53928,0.265,5.370000e+09,3.3,http://www.vietinbank.vn,CTG
2,HOSE,Ngân hàng,25183,0.234,5.589100e+09,3.0,https://vietcombank.com.vn,VCB
3,HOSE,Ngân hàng,60034,0.300,4.466700e+09,3.0,https://www.acb.com.vn,ACB
4,HOSE,Ngân hàng,121463,0.232,5.287100e+09,3.5,https://www.mbbank.com.vn,MBB
5,HOSE,Ngân hàng,18427,0.182,2.907600e+09,3.0,https://hdbank.com.vn,HDB
6,HOSE,Ngân hàng,28380,0.300,2.642000e+09,3.2,https://tpb.vn,TPB
7,HOSE,Ngân hàng,46009,0.247,7.933900e+09,2.8,https://www.vpbank.com.vn,VPB
8,HOSE,Ngân hàng,85855,0.234,1.885200e+09,3.0,http://www.sacombank.com.vn,STB
9,HOSE,Ngân hàng,1901,0.219,7.045000e+09,3.2,https://techcombank.com,TCB
10,HOSE,Ngân hàng,88267,0.029,3.662900e+09,2.7,https://www.shb.com.vn,SHB
11,HOSE,Ngân hàng,29187,0.154,2.536800e+09,2.9,https://www.vib.com.vn,VIB
12,UPCOM,Ngân hàng,28276,0.164,1.035000e+09,2.1,http://www.abbank.vn,ABB
13,HOSE,Ngân hàng,41294,0.006,2.557600e+09,2.7,https://lpbank.com.vn,LPB
14,HOSE,Dịch vụ tài chính,12142,0.010,3.360000e+08,2.8,https://tpbs.com.vn,ORS
15,HOSE,Dịch vụ tài chính,45044,0.050,6.694000e+08,2.6,https://www.vixs.vn,VIX
16,HNX,Dịch vụ tài chính,17654,0.027,4.377000e+08,2.6,http://mbs.com.vn,MBS
17,HOSE,Dịch vụ tài chính,63488,0.124,1.522300e+09,2.5,http://www.vndirect.com.vn,VND
18,HOSE,Dịch vụ tài chính,74489,0.429,1.511100e+09,2.4,https://www.ssi.com.vn,SSI
19,HOSE,Bán lẻ,41908,0.468,1.462200e+09,2.3,https://mwg.vn,MWG
20,HOSE,Thực phẩm và đồ uống,0,0.518,2.090000e+09,2.6,https://www.vinamilk.com.vn,VNM
21,HOSE,Tài nguyên Cơ bản,165914,0.222,6.396300e+09,2.7,http://www.hoaphat.com.vn,HPG
22,HOSE,Bất động sản,31513,0.138,4.354400e+09,3.5,https://vinhomes.vn/vi,VHM
23,HOSE,Công nghệ Thông tin,121463,0.463,1.460400e+09,3.2,https://www.fpt.com.vn,FPT
24,HOSE,Thực phẩm và đồ uống,13111,0.289,1.438400e+09,2.0,https://www.masangroup.com,MSN
25,HOSE,"Điện, nước & xăng dầu khí đốt",6390,0.018,2.296700e+09,2.7,https://www.pvgas.com.vn,GAS
26,HOSE,Bất động sản,25781,0.216,2.328800e+09,2.8,https://vincom.com.vn,VRE
27,HOSE,Du lịch và Giải trí,6067,0.135,5.416000e+08,1.9,http://www.vietjetair.com,VJC
28,HOSE,Bất động sản,54638,0.102,3.823700e+09,2.0,http://www.vingroup.net,VIC
29,HOSE,Dầu khí,15626,0.177,1.293900e+09,2.2,https://www.petrolimex.com.vn,PLX
30,HOSE,Thực phẩm và đồ uống,8675,0.608,1.282600e+09,2.9,https://www.sabeco.com.vn,SAB
31,HOSE,"Điện, nước & xăng dầu khí đốt",59226,0.038,2.341900e+09,2.4,https://pvpower.vn,POW
32,HOSE,Hóa chất,22532,0.005,4.000000e+09,2.9,https://vnrubbergroup.com,GVR
33,HOSE,Bất động sản,6292,0.020,1.035000e+09,2.4,https://becamex.com.vn,BCM
34,HOSE,Bất động sản,38320,0.060,6.682000e+08,2.7,https://www.hoanghuy.vn,TCH
35,HNX,Bất động sản,58579,0.050,5.404000e+08,2.2,http://ceogroup.com.vn,CEO
36,HNX,Ô tô và phụ tùng,21787,0.016,8.925000e+08,2.0,https://tasco.com.vn,HUT
37,HOSE,Bất động sản,77191,0.047,1.950100e+09,2.2,http://www.novaland.com.vn,NVL
38,HOSE,Thực phẩm và đồ uống,0,0.121,3.347000e+08,2.4,http://www.dabaco.com.vn,DBC
39,HNX,Thực phẩm và đồ uống,364,0.034,1.200000e+07,3.1,http://www.safocofood.com,SAF
40,HOSE,Hàng & Dịch vụ Công nghiệp,8210,0.072,1.218000e+08,3.2,https://viettelpost.com.vn,VTP
41,HOSE,Hàng & Dịch vụ Công nghiệp,18285,0.133,3.560000e+08,2.7,http://www.pvtrans.com,PVT
42,HOSE,Bán lẻ,11248,0.374,1.362000e+08,2.1,https://frt.vn,FRT
43,HOSE,Hóa chất,944,0.181,3.798000e+08,3.2,http://ducgiangchem.vn,DGC
44,HOSE,Hóa chất,14391,0.074,5.294000e+08,2.8,https://www.pvcfc.com.vn,DCM
45,HOSE,Tài nguyên Cơ bản,36861,0.093,2.633000e+08,2.1,https://tonnamkim.com/,NKG
46,HNX,Ô tô và phụ tùng,383,0.008,4.600000e+06,NaN,http://www.cmci.com.vn,CMC
47,UPCOM,Viễn thông,9648,0.000,3.043800e+09,2.6,http://www.viettelglobal.vn,VGI
48,HNX,Dầu khí,0,0.002,8.120000e+07,2.3,https://pvchem.com.vn,PVC

In [8]:
# df_company_overviews[df_company_overviews["industry"]=='Thực phẩm và đồ uống']

In [9]:
company_profiles = []

for symbol in vn30_symbols:
    company = Vnstock().stock(symbol=symbol, source='TCBS').company
    company_profile = company.profile()
    company_profile['symbol'] = symbol
    company_profiles.append(company_profile)

df_company_profiles = pd.concat(company_profiles, ignore_index=True)

# Display the concatenated DataFrame
df_company_profiles.head()

,company_name,company_profile,history_dev,company_promise,business_risk,key_developments,business_strategies,symbol
0,Ngân hàng Thương mại Cổ phần Á Châu,Ngân hàng Thương mại Cổ phần Á Châu (ACB) đượ...,Ngày 24/04/1993: Ngân hàng Thương mại Cổ phầ...,Chuyển đổi số trong lĩnh vực tài chính - ngân...,Bất ổn vĩ mô: Kinh tế Việt Nam được đánh giá...,Huy động vốn (nhận tiền gửi của khách hàng) ...,Áp dụng công nghệ tiên tiến hiện đại trong c...,ACB
1,Tổng Công ty Đầu tư và Phát triển Công nghiệp ...,Tổng Công ty Đầu tư và Phát triển Công nghiệp ...,Năm 1976: Công ty Thương Nghiệp Tổng Hợp Bến...,Việt Nam là một trong những thị trường mới n...,"Hiện nay, mặc dù kinh tế thế giới và trong n...",Phát triển và kinh doanh các khu công nghiệp...,Tiếp tục có những giải pháp mới trong việc k...,BCM
2,Ngân hàng Thương mại Cổ phần Đầu tư và Phát tr...,Ngân hàng Thương mại Cổ phần Đầu tư và Phát tr...,Ngày 26/04/1957: Tiền thân là Ngân hàng Kiến...,,Thông tư 36/2014/TT-NHNN cũng gây ra một số ...,Dịch vụ tài khoản Dịch vụ huy động vốn (tiền...,Tích cực tái cấu trúc nguồn vốn theo hướng g...,BID
3,Tập đoàn Bảo Việt,Tập đoàn Bảo Việt (BVH) có tiền thân là Công ...,Ngày 17/12/1964: Tiền thân là Công ty Bảo hi...,"Trong thời kỳ khủng hoảng kinh tế, bảo hiểm ...",Bảo hiểm nhân thọ là thị trường có tiềm năng...,Bảo hiểm nhân thọ; Bảo hiểm phi nhân thọ; Tá...,Mục tiêu của Bảo Việt là trở thành Tập đoàn ...,BVH
4,Ngân hàng Thương mại Cổ phần Công thương Việt Nam,Ngân hàng Thương mại Cổ phần Công thương Việt ...,1988: Ngân hàng Công thương Việt Nam được th...,,Khó duy trì được tốc độ tăng trưởng cao như ...,Dịch vụ ngân hàng bán buôn và bán lẻ trong v...,Phát triển thành một ngân hàng đa năng hiện ...,CTG

In [10]:
# Combine all features into a single column with the specified format
df_company_profiles['combine_profile'] = df_company_profiles.apply(
    lambda row: '\n '.join([f"{col}: {row[col]}" for col in df_company_profiles.columns if col != 'symbol']), axis=1
)

# Display the updated DataFrame
df_company_profiles.head()

,company_name,company_profile,history_dev,company_promise,business_risk,key_developments,business_strategies,symbol,combine_profile
0,Ngân hàng Thương mại Cổ phần Á Châu,Ngân hàng Thương mại Cổ phần Á Châu (ACB) đượ...,Ngày 24/04/1993: Ngân hàng Thương mại Cổ phầ...,Chuyển đổi số trong lĩnh vực tài chính - ngân...,Bất ổn vĩ mô: Kinh tế Việt Nam được đánh giá...,Huy động vốn (nhận tiền gửi của khách hàng) ...,Áp dụng công nghệ tiên tiến hiện đại trong c...,ACB,company_name: Ngân hàng Thương mại Cổ phần Á C...
1,Tổng Công ty Đầu tư và Phát triển Công nghiệp ...,Tổng Công ty Đầu tư và Phát triển Công nghiệp ...,Năm 1976: Công ty Thương Nghiệp Tổng Hợp Bến...,Việt Nam là một trong những thị trường mới n...,"Hiện nay, mặc dù kinh tế thế giới và trong n...",Phát triển và kinh doanh các khu công nghiệp...,Tiếp tục có những giải pháp mới trong việc k...,BCM,company_name: Tổng Công ty Đầu tư và Phát triể...
2,Ngân hàng Thương mại Cổ phần Đầu tư và Phát tr...,Ngân hàng Thương mại Cổ phần Đầu tư và Phát tr...,Ngày 26/04/1957: Tiền thân là Ngân hàng Kiến...,,Thông tư 36/2014/TT-NHNN cũng gây ra một số ...,Dịch vụ tài khoản Dịch vụ huy động vốn (tiền...,Tích cực tái cấu trúc nguồn vốn theo hướng g...,BID,company_name: Ngân hàng Thương mại Cổ phần Đầu...
3,Tập đoàn Bảo Việt,Tập đoàn Bảo Việt (BVH) có tiền thân là Công ...,Ngày 17/12/1964: Tiền thân là Công ty Bảo hi...,"Trong thời kỳ khủng hoảng kinh tế, bảo hiểm ...",Bảo hiểm nhân thọ là thị trường có tiềm năng...,Bảo hiểm nhân thọ; Bảo hiểm phi nhân thọ; Tá...,Mục tiêu của Bảo Việt là trở thành Tập đoàn ...,BVH,company_name: Tập đoàn Bảo Việt\n company_prof...
4,Ngân hàng Thương mại Cổ phần Công thương Việt Nam,Ngân hàng Thương mại Cổ phần Công thương Việt ...,1988: Ngân hàng Công thương Việt Nam được th...,,Khó duy trì được tốc độ tăng trưởng cao như ...,Dịch vụ ngân hàng bán buôn và bán lẻ trong v...,Phát triển thành một ngân hàng đa năng hiện ...,CTG,company_name: Ngân hàng Thương mại Cổ phần Côn...

In [11]:
print(df_company_profiles.combine_profile[1])

company_name: Tổng Công ty Đầu tư và Phát triển Công nghiệp - CTCP
 company_profile: Tổng Công ty Đầu tư và Phát triển Công nghiệp (BCM) có tiền thân là Công ty Thương Nghiệp Tổng Hợp Bến Cát (Becamex), được thành lập vào năm 1976. Tổng công ty hoạt động trong lĩnh vực đầu tư phát triển công nghiệp - đô thị, xây dựng dân dụng - công nghiệp - giao thông. Becamex IDC đang xây dựng và đưa vào sử dụng 40.000 căn hộ trong dự án tổng thể cung cấp 102.000 căn hộ cho 248.000 người ở Thuận An, Thủ Dầu Một, Bến Cát và Bàu Bàng. BCM được niêm yết trên Sở Giao dịch Chứng khoán Thành phố Hồ Chí Minh (HOSE) từ cuối tháng 07/2020.
 history_dev:   Năm 1976: Công ty Thương Nghiệp Tổng Hợp Bến Cát (Becamex) được thành lập; Năm 1992: Sáp nhập với các công ty cấp Tỉnh lấy tên chính thức là công ty Thương mại - XNK Tỉnh Sông Bé (Becamex); Năm 1999: Đổi tên thành Công ty Thương Mại - Đầu Tư và Phát Triển (tên giao dịch là BECAMEX Corp.); Ngày 28/04/2006: Công ty Đầu Tư và Phát Triển Công Nghiệp (Becamex IDC Corp.) được thành lập trên cơ sở sắp xếp và tổ chức lại hoạt động của Công ty Thương mại Đầu tư và Phát triển (Becamex) theo Quyết định số 106/2006/QĐ-UBND của UBND tỉnh Bình Dương; Ngày 19/01/2010: Chuyển thành Tổng Công ty Đầu tư và Phát triển Công nghiệp hoạt động theo hình thức công ty mẹ- công ty con; Ngày 21/02/2018: Giao dịch trên thị trường UPCOM; Ngày 27/09/2018: Chuyển đổi thành Tổng Công ty Đầu tư và Phát triển Công nghiệp - CTCP với vốn điều lệ 10.125.811.000.000 đồng theo Giấy chứng nhận đăng ký doanh nghiệp sô 3700145020 cấp thay đổi lần thứ 5 bởi Sở Kế hoạch và Đầu tư Tỉnh Bình Dương; Tháng 7/2019: Tăng vốn điều lệ lên 10.350.000 đồng; Ngày 31/07/2020: Niêm yết trên Sở Giao dịch Chứng khoán Thành phố Hồ Chí Minh (HOSE); Ngày 31/08/2020: Giao dịch trên Sở Giao dịch Chứng khoán Thành phố Hồ Chí Minh (HOSE);
 company_promise:   Việt Nam là một trong những thị trường mới nổi hấp dẫn, thu hút đầu tư nước ngoài với những lợi thế như giá bất động sản công nghiệp rẻ, môi trường chính trị ổn định, kinh tế đang phát triển, nguồn nhân công trẻ, dồi dào cộng thêm vị trí thuận lợi về giao thông, cửa ngõ của các hoạt động giao thương quốc tế. Chính phủ tạo môi trường thuận lợi cho các nhà đầu tư bằng cách chú trọng công tác nâng cấp và phát triển cơ sở hạ tầng tại các khu công nghiệp. Việc tham gia đàm phán, ký kết các Hiệp định thương mại, Hiệp định Thương mại tự do Việt Nam - EU, Hiệp định thương mại tự do với liên minh Hải quan Nga, Belarus, Kazakhstan và Hiệp định thương mại tự do với các nước ASEAN là cơ hội lớn cho làn sóng dịch chuyển của các doanh nghiệp quốc tế vào Việt Nam. Do đó, nhu cầu sử dụng các khu công nghiệp sẽ gia tăng mạnh trong tương lai.
 business_risk:   Hiện nay, mặc dù kinh tế thế giới và trong nước đã có những dấu hiệu tích cực, tuy nhiên,tình hình khó khăn chung và những thay đổi về cơ chế chính sách cũng sẽ ảnh hưởng đến Tổng Công ty trong giai đoạn đầu khi chuyển sang hình thức cổ phần. Doanh nghiệp cũng có khả năng chịu ảnh hưởng của các yếu tố rủi ro tài chính như rủi ro thanh khoản, rủi ro tỷ giá, rủi ro lãi suất, rủi ro từ giá cổ phiếu. Tổng Công ty sẽ phải đối mặt với sự cạnh tranh khốc liệt từ các đối thủ cạnh tranh do sự phát triển của ngành bất động sản trong nước.
 key_developments:   Phát triển và kinh doanh các khu công nghiệp và đô thị; Phát triển cơ sở hạ tầng giao thông; Phát triển đô thị và dịch vụ; Phát triển nhà ở xã hội; Đầu tư phát triển giáo dục - y tế; Phát triển thành phố thông minh (Smart city);
 business_strategies:   Tiếp tục có những giải pháp mới trong việc kiến tạo hạ tầng kinh tế - xã hội, tập trung xây dựng thành phố thông minh, hướng đến xây dựng Bình Dương trở thành một đầu tàu kinh tế của khu vực trọng điểm phía Nam; Tiếp tục tạo ra các sản phẩm có chất lượng cao nhằm tối đa hóa lợi ích cho doanh nghiệp và khách hàng; Nâng cao hiệu quả quản trị và chất lượng quản lý để giúp doanh nghiệp gia tăng được giá trị thương hiệu và phát triển bền vững; Thiết lập và tăng cường mối liên kết và chặt chẽ và hỗ trợ lẫn nhau giữa các công ty thành viên trong tổ hợp công ty mẹ - công ty con.

In [12]:
df_company_profiles.drop(columns = ['company_profile','company_profile','history_dev','company_promise','business_risk','key_developments','business_strategies'], inplace = True)

In [13]:
df_company_profiles.head()

,company_name,symbol,combine_profile
0,Ngân hàng Thương mại Cổ phần Á Châu,ACB,company_name: Ngân hàng Thương mại Cổ phần Á C...
1,Tổng Công ty Đầu tư và Phát triển Công nghiệp ...,BCM,company_name: Tổng Công ty Đầu tư và Phát triể...
2,Ngân hàng Thương mại Cổ phần Đầu tư và Phát tr...,BID,company_name: Ngân hàng Thương mại Cổ phần Đầu...
3,Tập đoàn Bảo Việt,BVH,company_name: Tập đoàn Bảo Việt\n company_prof...
4,Ngân hàng Thương mại Cổ phần Công thương Việt Nam,CTG,company_name: Ngân hàng Thương mại Cổ phần Côn...

In [14]:
# Concatenate df_company_overviews and df_company_profiles based on the 'symbol' column
df_company_info = pd.merge(df_company_overviews, df_company_profiles, on='symbol')

# Display the concatenated DataFrame
df_company_info.head()

,exchange,industry,no_shareholders,foreign_percent,issue_share,stock_rating,website,symbol,company_name,combine_profile
0,HOSE,Ngân hàng,60034,0.300,4.466700e+09,3.0,https://www.acb.com.vn,ACB,Ngân hàng Thương mại Cổ phần Á Châu,company_name: Ngân hàng Thương mại Cổ phần Á C...
1,HOSE,Bất động sản,6292,0.020,1.035000e+09,2.3,https://becamex.com.vn,BCM,Tổng Công ty Đầu tư và Phát triển Công nghiệp ...,company_name: Tổng Công ty Đầu tư và Phát triể...
2,HOSE,Ngân hàng,27603,0.172,5.700400e+09,2.9,https://www.bidv.com.vn,BID,Ngân hàng Thương mại Cổ phần Đầu tư và Phát tr...,company_name: Ngân hàng Thương mại Cổ phần Đầu...
3,HOSE,Bảo hiểm,8682,0.265,7.423000e+08,2.4,https://www.baoviet.com.vn,BVH,Tập đoàn Bảo Việt,company_name: Tập đoàn Bảo Việt\n company_prof...
4,HOSE,Ngân hàng,53928,0.266,5.370000e+09,3.1,http://www.vietinbank.vn,CTG,Ngân hàng Thương mại Cổ phần Công thương Việt Nam,company_name: Ngân hàng Thương mại Cổ phần Côn...

In [15]:
name = stock.listing.symbols_by_exchange()
name

,symbol,id,type,exchange,en_organ_name,en_organ_short_name,organ_short_name,organ_name
0,YTC,8425620,STOCK,UPCOM,Ho Chi Minh City Medical Import Export Joint S...,YTECO,XNK Y tế TP.HCM,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...
1,YEG,8424579,STOCK,HSX,Yeah1 Group Corporation,Yeah1 Group,Tập đoàn Yeah1,Công ty Cổ phần Tập đoàn Yeah1
2,YBM,8424470,STOCK,HSX,Yen Bai Industry Mineral Joint Stock Company,Yen Bai Industry Mineral,Khoáng sản CN Yên Bái,Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
3,YBC,8425710,STOCK,UPCOM,YenBai Cement and Minerals Joint Stock Company,YenBai Cement and Minerals,Xi măng và Khoáng sản Yên Bái,Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
4,XPH,8425864,STOCK,UPCOM,Hanoi Soap Joint Stock Company,Hanoi Soap,Xà phòng Hà Nội,Công ty Cổ phần Xà phòng Hà Nội
...,...,...,...,...,...,...,...,...
2550,AAS,8425599,STOCK,UPCOM,Smart Invest Securities Joint Stock Company,SmartInvest Securities,Chứng khoán SmartInvest,Công ty Cổ phần Chứng khoán SmartInvest
2551,AAM,8424957,STOCK,HSX,Mekong Fisheries Joint Stock Company,Mekong Fisheries,Thủy sản Mekong,Công ty Cổ Phần Thủy Sản MeKong
2552,AAH,13216673,STOCK,UPCOM,Hop Nhat Joint Stock Company,Hop Nhat Coal,Than Hợp Nhất,Công ty Cổ phần Hợp Nhất
2553,AAA,8424464,STOCK,HSX,An Phat Bioplastics Joint Stock Company,An Phat Bioplastics,An Phát Bioplastics,Công ty Cổ phần Nhựa An Phát Xanh
2554,A32,8425330,STOCK,UPCOM,32 Joint Stock Company,32 Company,Công ty 32,Công ty Cổ phần 32

In [16]:
# Merge df_company_info with name DataFrame to add en_organ_name and en_organ_short_name columns
df_company_info = pd.merge(df_company_info, name[['symbol', 'en_organ_name', 'en_organ_short_name', 'organ_short_name']], on='symbol', how='left')

# Display the updated DataFrame
df_company_info

,exchange,industry,no_shareholders,foreign_percent,issue_share,stock_rating,website,symbol,company_name,combine_profile,en_organ_name,en_organ_short_name
0,HOSE,Ngân hàng,60034,0.300,4.466700e+09,3.0,https://www.acb.com.vn,ACB,Ngân hàng Thương mại Cổ phần Á Châu,company_name: Ngân hàng Thương mại Cổ phần Á C...,Asia Commercial Joint Stock Bank,Asia Commercial Bank
1,HOSE,Bất động sản,6292,0.020,1.035000e+09,2.3,https://becamex.com.vn,BCM,Tổng Công ty Đầu tư và Phát triển Công nghiệp ...,company_name: Tổng Công ty Đầu tư và Phát triể...,Investment and Industrial Development Joint St...,Becamex IDC Corp.
2,HOSE,Ngân hàng,27603,0.172,5.700400e+09,2.9,https://www.bidv.com.vn,BID,Ngân hàng Thương mại Cổ phần Đầu tư và Phát tr...,company_name: Ngân hàng Thương mại Cổ phần Đầu...,Joint Stock Commercial Bank for Investment and...,BIDV
3,HOSE,Bảo hiểm,8682,0.265,7.423000e+08,2.4,https://www.baoviet.com.vn,BVH,Tập đoàn Bảo Việt,company_name: Tập đoàn Bảo Việt\n company_prof...,Bao Viet Holdings,Bao Viet Group
4,HOSE,Ngân hàng,53928,0.266,5.370000e+09,3.1,http://www.vietinbank.vn,CTG,Ngân hàng Thương mại Cổ phần Công thương Việt Nam,company_name: Ngân hàng Thương mại Cổ phần Côn...,Vietnam Joint Stock Commercial Bank For Indust...,VietinBank
5,HOSE,Công nghệ Thông tin,121463,0.463,1.460400e+09,3.1,https://www.fpt.com.vn,FPT,Công ty Cổ phần FPT,company_name: Công ty Cổ phần FPT\n company_pr...,FPT Corporation,FPT Corp
6,HOSE,"Điện, nước & xăng dầu khí đốt",6390,0.019,2.296700e+09,2.8,https://www.pvgas.com.vn,GAS,Tổng Công ty Khí Việt Nam - Công ty Cổ phần,company_name: Tổng Công ty Khí Việt Nam - Công...,PetroVietnam Gas Joint Stock Corporation,PetroVietnam Gas
7,HOSE,Hóa chất,22532,0.005,4.000000e+09,2.7,https://vnrubbergroup.com,GVR,Tập đoàn Công nghiệp Cao su Việt Nam - Công ty...,company_name: Tập đoàn Công nghiệp Cao su Việt...,Viet Nam Rubber Group - Joint Stock Company,Viet Nam Rubber Group
8,HOSE,Ngân hàng,18427,0.187,2.907600e+09,2.9,https://hdbank.com.vn,HDB,Ngân hàng Thương mại Cổ phần Phát Triển Thành ...,company_name: Ngân hàng Thương mại Cổ phần Phá...,Ho Chi Minh City Development Joint Stock Comme...,HDBank
9,HOSE,Tài nguyên Cơ bản,165914,0.220,6.396300e+09,2.6,http://www.hoaphat.com.vn,HPG,Công ty Cổ phần Tập đoàn Hòa Phát,company_name: Công ty Cổ phần Tập đoàn Hòa Phá...,Hoa Phat Group Joint Stock Company,Hoa Phat Group
10,HOSE,Ngân hàng,121463,0.232,5.287100e+09,3.4,https://www.mbbank.com.vn,MBB,Ngân hàng Thương mại Cổ phần Quân đội,company_name: Ngân hàng Thương mại Cổ phần Quâ...,Military Commercial Joint Stock Bank,MBBank
11,HOSE,Thực phẩm và đồ uống,13111,0.282,1.438400e+09,1.9,https://www.masangroup.com,MSN,Công ty Cổ phần Tập đoàn Masan,company_name: Công ty Cổ phần Tập đoàn Masan\n...,Masan Group Corporation,Masan Group
12,HOSE,Bán lẻ,41908,0.470,1.462200e+09,2.2,https://mwg.vn,MWG,Công ty Cổ phần Đầu tư Thế Giới Di Động,company_name: Công ty Cổ phần Đầu tư Thế Giới ...,Mobile World Investment Corporation,Mobile World Investment
13,HOSE,Dầu khí,15626,0.180,1.293900e+09,2.5,https://www.petrolimex.com.vn,PLX,Tập đoàn Xăng dầu Việt Nam,company_name: Tập đoàn Xăng dầu Việt Nam\n com...,Vietnam National Petroleum Group,Petrolimex
14,HOSE,"Điện, nước & xăng dầu khí đốt",59226,0.038,2.341900e+09,2.3,https://pvpower.vn,POW,Tổng Công ty Điện lực Dầu khí Việt Nam - CTCP,company_name: Tổng Công ty Điện lực Dầu khí Vi...,PetroVietnam Power Corporation,PV Power
15,HOSE,Thực phẩm và đồ uống,8675,0.608,1.282600e+09,2.4,https://www.sabeco.com.vn,SAB,Tổng Công ty Cổ phần Bia - Rượu - Nước Giải kh...,company_name: Tổng Công ty Cổ phần Bia - Rượu ...,Saigon Beer - Alcohol - Beverage Corporation,SABECO
16,HOSE,Ngân hàng,88267,0.030,3.662900e+09,2.7,https://www.shb.com.vn,SHB,Ngân hàng Thương mại Cổ phần Sài Gòn – Hà Nội,company_name: Ngân hàng Thương mại Cổ phần Sài...,Saigon-Hanoi Commercial Joint Stock Bank,SH Bank
17,HOSE,Ngân hàng,6107,0.001,2.835000e+09,2.5,https://www.seabank.com.vn,SSB,Ngân hàng Thương mại Cổ phần Đông Nam Á,company_name: Ngân hàng Thương mại Cổ phần Đôn...,Southeast Asia Commercial Joint Stock Bank,SeABank
18,HOSE,Dịch vụ tài chính,74489,0.431,1.511100e+09,2.5,https://www.ssi.com.vn,SSI,Công ty Cổ phần Chứng khoán SSI,company_name: Công ty Cổ phần Chứng khoán SSI\...,SSI Securities Corporation,SSI Securities
19,HOSE,Ngân hàng,85855,0.237,1.885200e+09,2.9,http://www.sacombank.com.vn,STB,Ngân hàng Thương mại Cổ phần Sài Gòn Thương Tín,company_name: Ngân hàng Thương mại Cổ phần Sài...,SaiGon Thuong Tin Commercial Joint Stock Bank,Sacombank
20,HOSE,Ngân hàng,1901,0.215,7.045000e+09,3.2,https://techcombank.com,TCB,Ngân hàng Thương mại Cổ phần Kỹ thương Việt Nam,company_name: Ngân hàng Thương mại Cổ phần Kỹ ...,Vietnam Technological And Commercial Joint Sto...,Techcombank
21,HOSE,Ngân hàng,28380,0.300,2.201600e+09,3.1,https://tpb.vn,TPB,Ngân hàng Thương mại Cổ phần Tiên Phong,company_name: Ngân hàng Thương mại Cổ phần Tiê...,Tien Phong Commercial Joint Stock Bank,TPBank
22,HOSE,Ngân hàng,25183,0.234,5.589100e+09,3.0,https://vietcombank.com.vn,VCB,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...,company_name: Ngân hàng Thương mại Cổ phần Ngo...,Joint Stock Commercial Bank For Foreign Trade ...,Vietcombank
23,HOSE,Bất động sản,31513,0.140,4.354400e+09,3.0,https://vinhomes.vn/vi,VHM,Công ty Cổ phần Vinhomes,company_name: Công ty Cổ phần Vinhomes\n compa...,Vinhomes Joint Stock Company,Vinhomes
24,HOSE,Ngân hàng,29187,0.154,2.536800e+09,2.8,https://www.vib.com.vn,VIB,Ngân hàng Thương mại Cổ phần Quốc tế Việt Nam,company_name: Ngân hàng Thương mại Cổ phần Quố...,Viet Nam International Commercial Joint Stock ...,VIBBank
25,HOSE,Bất động sản,54638,0.102,3.823700e+09,1.9,http://www.vingroup.net,VIC,Tập đoàn Vingroup - Công ty CP,company_name: Tập đoàn Vingroup - Công ty CP\n...,VinGroup Joint Stock Company,VinGroup
26,HOSE,Du lịch và Giải trí,6067,0.135,5.416000e+08,2.1,http://www.vietjetair.com,VJC,Công ty Cổ phần Hàng không Vietjet,company_name: Công ty Cổ phần Hàng không Vietj...,VietJet Aviation Joint Stock Company,Vietjet Air
27,HOSE,Thực phẩm và đồ uống,0,0.519,2.090000e+09,2.6,https://www.vinamilk.com.vn,VNM,Công ty Cổ phần Sữa Việt Nam,company_name: Công ty Cổ phần Sữa Việt Nam\n c...,Vietnam Dairy Products Joint Stock Company,Vinamilk
28,HOSE,Ngân hàng,46009,0.252,7.933900e+09,2.7,https://www.vpbank.com.vn,VPB,Ngân hàng Thương mại Cổ phần Việt Nam Thịnh Vượng,company_name: Ngân hàng Thương mại Cổ phần Việ...,Vietnam Prosperity Joint Stock Commercial Bank,VPBank
29,HOSE,Bất động sản,25781,0.218,2.328800e+09,2.8,https://vincom.com.vn,VRE,Công ty Cổ phần Vincom Retail,company_name: Công ty Cổ phần Vincom Retail\n ...,Vincom Retail Joint Stock Company,Vincom Retail

In [17]:
df_company_info.rename(columns = {'symbol':'stock_code',  'en_organ_name':'en_company_name', 'en_organ_short_name':'en_short_name', 'organ_short_name':'short_name'}, inplace = True)

In [18]:
df_company_info= df_company_info[['stock_code','company_name','en_company_name','en_short_name','combine_profile','industry','exchange','foreign_percent','issue_share','no_shareholders','stock_rating','website']]
df_company_info.head()

,stock_code,company_name,en_company_name,en_short_name,combine_profile,industry,exchange,foreign_percent,issue_share,no_shareholders,stock_rating,website
0,ACB,Ngân hàng Thương mại Cổ phần Á Châu,Asia Commercial Joint Stock Bank,Asia Commercial Bank,company_name: Ngân hàng Thương mại Cổ phần Á C...,Ngân hàng,HOSE,0.300,4.466700e+09,60034,3.0,https://www.acb.com.vn
1,BCM,Tổng Công ty Đầu tư và Phát triển Công nghiệp ...,Investment and Industrial Development Joint St...,Becamex IDC Corp.,company_name: Tổng Công ty Đầu tư và Phát triể...,Bất động sản,HOSE,0.020,1.035000e+09,6292,2.3,https://becamex.com.vn
2,BID,Ngân hàng Thương mại Cổ phần Đầu tư và Phát tr...,Joint Stock Commercial Bank for Investment and...,BIDV,company_name: Ngân hàng Thương mại Cổ phần Đầu...,Ngân hàng,HOSE,0.172,5.700400e+09,27603,2.9,https://www.bidv.com.vn
3,BVH,Tập đoàn Bảo Việt,Bao Viet Holdings,Bao Viet Group,company_name: Tập đoàn Bảo Việt\n company_prof...,Bảo hiểm,HOSE,0.265,7.423000e+08,8682,2.4,https://www.baoviet.com.vn
4,CTG,Ngân hàng Thương mại Cổ phần Công thương Việt Nam,Vietnam Joint Stock Commercial Bank For Indust...,VietinBank,company_name: Ngân hàng Thương mại Cổ phần Côn...,Ngân hàng,HOSE,0.266,5.370000e+09,53928,3.1,http://www.vietinbank.vn

In [20]:
df_company_info.to_csv('sample_data\df_company_info.csv', index=False)

invalid escape sequence '\d'
invalid escape sequence '\d'
invalid escape sequence '\d'

In [21]:
company_shareholders = []

for symbol in vn30_symbols:
    company = Vnstock().stock(symbol=symbol, source='TCBS').company
    company_shareholder = company.shareholders()
    company_shareholder['symbol'] = symbol
    company_shareholders.append(company_shareholder)

df_company_shareholders = pd.concat(company_shareholders, ignore_index=True)

# Display the concatenated DataFrame
df_company_shareholders

                                   share_holder  share_own_percent symbol
0                                 Trần Hùng Huy             0.0394    ACB
1                                 Đặng Thu Thủy             0.0137    ACB
2                      Nguyễn Thiên Hương Jenny             0.0134    ACB
3                                   Đặng Thu Hà             0.0119    ACB
4                        Nguyễn Đức Hiếu Johnny             0.0107    ACB
..                                          ...                ...    ...
220                             Nguyễn Thu Thủy             0.0256    VPB
221                                        Khác             0.1743    VPB
222  Công ty Cổ phần Kinh Doanh Thương Mại Sado             0.4050    VRE
223              Tập đoàn Vingroup - Công ty CP             0.1837    VRE
224                                        Khác             0.0931    VRE

[225 rows x 3 columns]

In [22]:
# VCI là nguồn dữ liệu từ CK Vietcap bên cạnh nguồn từ TCBS
listing_name = stock.listing.all_symbols()
listing_name

     ticker                                         organ_name
0       A32                                 Công ty Cổ phần 32
1       AAA                  Công ty Cổ phần Nhựa An Phát Xanh
2       AAM                    Công ty Cổ Phần Thủy Sản MeKong
3       AAS            Công ty Cổ phần Chứng khoán SmartInvest
4       AAT        Công ty Cổ phần Tập đoàn Tiên Sơn Thanh Hóa
...     ...                                                ...
1593    XPH                    Công ty Cổ phần Xà phòng Hà Nội
1594    YBC      Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
1595    YBM     Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
1596    YEG                     Công ty Cổ phần Tập đoàn Yeah1
1597    YTC  Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...

[1598 rows x 2 columns]

In [23]:
df_company_shareholders.share_holder.value_counts()

share_holder
Khác                                                             30
Tổng Công ty Đầu Tư Và Kinh Doanh Vốn Nhà Nước - Công ty TNHH     4
Ngân Hàng Nhà Nước Việt Nam                                       3
Uỷ ban Quản lý Vốn Nhà nước tại Doanh nghiệp                      2
Nguyễn Thị Thanh Thủy                                             2
                                                                 ..
Công Ty TNHH Một Thành Viên Xây Dựng Hoa Hướng Dương              1
Sk Investment Vina I Pte. Ltd.                                    1
Nguyễn Hoàng Yến                                                  1
Madhur Maini                                                      1
Công ty Cổ phần Kinh Doanh Thương Mại Sado                        1
Name: count, Length: 183, dtype: int64

In [24]:
# Create a copy of the original share_holder column
original_share_holder = df_company_shareholders['share_holder'].copy()

# Create a dictionary to map organ_name to ticker
organ_name_to_ticker = dict(zip(name['organ_name'], name['symbol']))

# Replace values in the share_holder column with the corresponding ticker values
df_company_shareholders['share_holder'] = df_company_shareholders['share_holder'].map(organ_name_to_ticker).fillna(df_company_shareholders['share_holder'])

# Find the rows where the share_holder value has changed
changed_value_share = df_company_shareholders[df_company_shareholders['share_holder'] != original_share_holder]

# Display the changed values
changed_value_share

    share_holder  share_own_percent symbol
147          MSN             0.1488    TCB
157          FPT             0.0677    TPB
170          VIC             0.6934    VHM
223          VIC             0.1837    VRE

In [25]:
df_company_shareholders.share_holder.value_counts()

share_holder
Khác                                                             30
Tổng Công ty Đầu Tư Và Kinh Doanh Vốn Nhà Nước - Công ty TNHH     4
Ngân Hàng Nhà Nước Việt Nam                                       3
Uỷ ban Quản lý Vốn Nhà nước tại Doanh nghiệp                      2
Nguyễn Thị Thanh Thủy                                             2
                                                                 ..
Công Ty TNHH Một Thành Viên Xây Dựng Hoa Hướng Dương              1
Sk Investment Vina I Pte. Ltd.                                    1
Nguyễn Hoàng Yến                                                  1
Madhur Maini                                                      1
Công ty Cổ phần Kinh Doanh Thương Mại Sado                        1
Name: count, Length: 183, dtype: int64

In [26]:
changed_value_share = changed_value_share.rename(columns = {'share_holder':'symbol','symbol':'sub_company_name'})

In [27]:
changed_value_share

    symbol  share_own_percent sub_company_name
147    MSN             0.1488              TCB
157    FPT             0.0677              TPB
170    VIC             0.6934              VHM
223    VIC             0.1837              VRE

In [28]:
# df_company_shareholders[df_company_shareholders['share_holder'] == 'Nguyễn Thị Thanh Thủy']

In [29]:
company_subsidiaries = []

for symbol in vn30_symbols:
    company = Vnstock().stock(symbol=symbol, source='TCBS').company
    company_subsidiary = company.subsidiaries()
    company_subsidiary['symbol'] = symbol
    company_subsidiaries.append(company_subsidiary)

df_company_subsidiaries = pd.concat(company_subsidiaries, ignore_index=True)

# Display the concatenated DataFrame
df_company_subsidiaries

                                      sub_company_name  sub_own_percent symbol
0                         Công ty TNHH Chứng khoán ACB            1.000    ACB
1    Công Ty TNHH Một Thành Viên Cho Thuê Tài Chính...            1.000    ACB
2                     Công ty TNHH MTV Quản Lý Quỹ ACB            1.000    ACB
3    Công ty TNHH Quản Lý Nợ Và Khai Thác Tài Sản N...            1.000    ACB
4    Ngân Hàng Thương Mại Cổ Phần Á Châu - Chi Nhán...            1.000    ACB
..                                                 ...              ...    ...
854                Công ty TNHH Vận Hành Vincom Retail            1.000    VRE
855             Công ty TNHH Vincom Retail Landmark 81            1.000    VRE
856                Công ty TNHH Vincom Retail Miền Nam            1.000    VRE
857               Công ty TNHH Bất động sản VINCOM NCT            1.000    VRE
858               Công ty Cổ Phần Đầu Tư Vincom Retail            0.999    VRE

[859 rows x 3 columns]

In [30]:
original_sub = df_company_subsidiaries['sub_company_name'].copy()

# Create a dictionary to map organ_name to ticker
organ_name_to_ticker_ = dict(zip(name['organ_name'], name['symbol']))

df_company_subsidiaries['sub_company_name'] = df_company_subsidiaries['sub_company_name'].map(organ_name_to_ticker_).fillna(df_company_subsidiaries['sub_company_name'])

changed_value_sub = df_company_subsidiaries[df_company_subsidiaries['sub_company_name'] != original_sub]

# Display the changed values
changed_value_sub

    sub_company_name  sub_own_percent symbol
5                PXS            0.181    ACB
9                BTS            0.051    ACB
10               VOS            0.049    ACB
11               DVC            0.036    ACB
12               ALT            0.030    ACB
..               ...              ...    ...
840              SBT            0.048    VNM
843              SRF            0.004    VNM
844              TDW            0.000    VNM
851              SGP            0.074    VPB
852              FDC            0.000    VPB

[251 rows x 3 columns]

In [31]:
changed_value_share = changed_value_share.rename(columns = {'share_own_percent':'sub_own_percent'})
changed_value_share

    symbol  sub_own_percent sub_company_name
147    MSN           0.1488              TCB
157    FPT           0.0677              TPB
170    VIC           0.6934              VHM
223    VIC           0.1837              VRE

In [32]:
# Concatenate the two DataFrames vertically
df_sub_and_shareholder = pd.concat([changed_value_share, changed_value_sub], ignore_index=True)

# Drop duplicates based on the 'symbol' column, keeping the first occurrence
df_sub_and_shareholder.drop_duplicates(subset=['symbol','sub_company_name'], keep='first', inplace=True)

# Display the resulting DataFrame
df_sub_and_shareholder

    symbol  sub_own_percent sub_company_name
0      MSN           0.1488              TCB
1      FPT           0.0677              TPB
2      VIC           0.6934              VHM
3      VIC           0.1837              VRE
4      ACB           0.1810              PXS
..     ...              ...              ...
250    VNM           0.0480              SBT
251    VNM           0.0040              SRF
252    VNM           0.0000              TDW
253    VPB           0.0740              SGP
254    VPB           0.0000              FDC

[252 rows x 3 columns]

In [37]:

df_sub_and_shareholder = df_sub_and_shareholder[['stock_code', 'sub_company_name', 'sub_own_percent']].reset_index(drop=True)

# Display the updated DataFrame
df_sub_and_shareholder.rename(columns={'symbol': 'stock_code'}, inplace=True)
df_sub_and_shareholder

    stock_code sub_company_name  sub_own_percent
0          MSN              TCB           0.1488
1          FPT              TPB           0.0677
2          VIC              VHM           0.6934
3          VIC              VRE           0.1837
4          ACB              PXS           0.1810
..         ...              ...              ...
247        VNM              SBT           0.0480
248        VNM              SRF           0.0040
249        VNM              TDW           0.0000
250        VPB              SGP           0.0740
251        VPB              FDC           0.0000

[252 rows x 3 columns]

In [38]:

df_sub_and_shareholder.rename(columns={'sub_company_name': 'invest_on','sub_own_percent':'percent' }, inplace=True)
df_sub_and_shareholder

    stock_code invest_on  percent
0          MSN       TCB   0.1488
1          FPT       TPB   0.0677
2          VIC       VHM   0.6934
3          VIC       VRE   0.1837
4          ACB       PXS   0.1810
..         ...       ...      ...
247        VNM       SBT   0.0480
248        VNM       SRF   0.0040
249        VNM       TDW   0.0000
250        VPB       SGP   0.0740
251        VPB       FDC   0.0000

[252 rows x 3 columns]

In [39]:
df_sub_and_shareholder.to_csv('sample_data\df_sub_and_shareholder.csv', index=False)

invalid escape sequence '\d'
invalid escape sequence '\d'
invalid escape sequence '\d'

# Name table

In [41]:
name.drop(columns=['id', 'type', 'exchange'], inplace=True)
name

,symbol,en_organ_name,en_organ_short_name,organ_short_name,organ_name
0,YTC,Ho Chi Minh City Medical Import Export Joint S...,YTECO,XNK Y tế TP.HCM,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...
1,YEG,Yeah1 Group Corporation,Yeah1 Group,Tập đoàn Yeah1,Công ty Cổ phần Tập đoàn Yeah1
2,YBM,Yen Bai Industry Mineral Joint Stock Company,Yen Bai Industry Mineral,Khoáng sản CN Yên Bái,Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
3,YBC,YenBai Cement and Minerals Joint Stock Company,YenBai Cement and Minerals,Xi măng và Khoáng sản Yên Bái,Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
4,XPH,Hanoi Soap Joint Stock Company,Hanoi Soap,Xà phòng Hà Nội,Công ty Cổ phần Xà phòng Hà Nội
...,...,...,...,...,...
2550,AAS,Smart Invest Securities Joint Stock Company,SmartInvest Securities,Chứng khoán SmartInvest,Công ty Cổ phần Chứng khoán SmartInvest
2551,AAM,Mekong Fisheries Joint Stock Company,Mekong Fisheries,Thủy sản Mekong,Công ty Cổ Phần Thủy Sản MeKong
2552,AAH,Hop Nhat Joint Stock Company,Hop Nhat Coal,Than Hợp Nhất,Công ty Cổ phần Hợp Nhất
2553,AAA,An Phat Bioplastics Joint Stock Company,An Phat Bioplastics,An Phát Bioplastics,Công ty Cổ phần Nhựa An Phát Xanh
2554,A32,32 Joint Stock Company,32 Company,Công ty 32,Công ty Cổ phần 32

In [42]:
name.rename(columns = {'symbol':'stock_code', 'organ_name':'company_name','en_organ_name':'en_company_name','en_organ_short_name':'en_short_name' ,'organ_short_name':'short_name'}, inplace = True)

In [43]:
name

,stock_code,en_company_name,en_short_name,short_name,company_name
0,YTC,Ho Chi Minh City Medical Import Export Joint S...,YTECO,XNK Y tế TP.HCM,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...
1,YEG,Yeah1 Group Corporation,Yeah1 Group,Tập đoàn Yeah1,Công ty Cổ phần Tập đoàn Yeah1
2,YBM,Yen Bai Industry Mineral Joint Stock Company,Yen Bai Industry Mineral,Khoáng sản CN Yên Bái,Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
3,YBC,YenBai Cement and Minerals Joint Stock Company,YenBai Cement and Minerals,Xi măng và Khoáng sản Yên Bái,Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
4,XPH,Hanoi Soap Joint Stock Company,Hanoi Soap,Xà phòng Hà Nội,Công ty Cổ phần Xà phòng Hà Nội
...,...,...,...,...,...
2550,AAS,Smart Invest Securities Joint Stock Company,SmartInvest Securities,Chứng khoán SmartInvest,Công ty Cổ phần Chứng khoán SmartInvest
2551,AAM,Mekong Fisheries Joint Stock Company,Mekong Fisheries,Thủy sản Mekong,Công ty Cổ Phần Thủy Sản MeKong
2552,AAH,Hop Nhat Joint Stock Company,Hop Nhat Coal,Than Hợp Nhất,Công ty Cổ phần Hợp Nhất
2553,AAA,An Phat Bioplastics Joint Stock Company,An Phat Bioplastics,An Phát Bioplastics,Công ty Cổ phần Nhựa An Phát Xanh
2554,A32,32 Joint Stock Company,32 Company,Công ty 32,Công ty Cổ phần 32

cổ tức

In [30]:
company_dividends = []
# Iterate through each symbol and print company information
for symbol in vn30_symbols:
    company = Vnstock().stock(symbol=symbol, source='TCBS').company
    company_dividend = company.dividends()
    company_dividend['symbol'] = symbol
    company_dividends.append(company_dividend)

df_company_dividends = pd.concat(company_dividends, ignore_index=True)
# Display the concatenated DataFrame
df_company_dividends

    exercise_date  cash_year  cash_dividend_percentage issue_method symbol
0        31/05/24       2023                     0.100         cash    ACB
1        31/05/24       2024                     0.150        share    ACB
2        01/06/23       2022                     0.100         cash    ACB
3        01/06/23       2023                     0.150        share    ACB
4        02/06/22       2022                     0.250        share    ACB
..            ...        ...                       ...          ...    ...
312      18/06/18       2018                     0.302        share    VPB
313      10/07/17       2017                     0.318        share    VPB
314      13/01/17       2017                     0.131        share    VPB
315      29/01/16       2016                     0.146        share    VPB
316      17/05/19       2018                     0.105         cash    VRE

[317 rows x 5 columns]

In [31]:
df_company_dividends = df_company_dividends[['symbol','exercise_date','cash_dividend_percentage','issue_method','cash_year']]
df_company_dividends

    symbol exercise_date  cash_dividend_percentage issue_method  cash_year
0      ACB      31/05/24                     0.100         cash       2023
1      ACB      31/05/24                     0.150        share       2024
2      ACB      01/06/23                     0.100         cash       2022
3      ACB      01/06/23                     0.150        share       2023
4      ACB      02/06/22                     0.250        share       2022
..     ...           ...                       ...          ...        ...
312    VPB      18/06/18                     0.302        share       2018
313    VPB      10/07/17                     0.318        share       2017
314    VPB      13/01/17                     0.131        share       2017
315    VPB      29/01/16                     0.146        share       2016
316    VRE      17/05/19                     0.105         cash       2018

[317 rows x 5 columns]

In [32]:
df_company_dividends.issue_method.value_counts()

issue_method
cash     216
share    101
Name: count, dtype: int64